### PR TITLE
added a single point prediction interface, fixed typo

### PR DESCRIPTION
**Pull request by Red-Portal**
Hi,
Currently GaussianProcesses.jl only provides inference of multiple points packed into a matrix.
I thought providing an interface for predicting single points would be convenient.
Also, I believe the square bracket in the comment is wrong?

### CODE REVIEW

**Comment by thomaspinder** [comment]
Thanks for this @Red-Portal. Unfortunately, assuming I've interpreted your pull-request correctly, if I am to run `predict_f(gp, 1.0)`, then I get an error. Are you able to look at this? As an aside, I'm not too sure why being able to make predictions on a float would be useful.

Thanks for picking up the typo. Once the above has been resolved, we'll merge that aspect.

**Comment by Red-Portal** [comment]
Hi @thomaspinder No, I didn't intend it to be used with scalars but rather vectors. The current interface I believe only receives matrices (multiple vector points). The interface I propose lets single vectors to be used without 'matrixification'.

**Comment by thomaspinder** [comment]
Hi @Red-Portal, I don't think that's true. With the current version I am able to run `predict_f(gp, [1.0])`.

**Comment by Red-Portal** [comment]
Hi, @thomaspinder that seems to be my mistake.
Sorry for the trouble.
I'll just fix the typo

**Comment by thomaspinder** [comment]
No problem @Red-Portal. Thanks for your help!

**Pull request merged**
