### PR TITLE
Functions to compute cross-validation metrics for GPE

### PR DESCRIPTION
**Pull request by maximerischard**
This is something I needed recently: a set of functions to compute cross-validation metrics and their derivatives (to optimize the hyperparameters wrt the CV metric instead of the marginal likelihood).

### CODE REVIEW

**Comment by chris-nemeth** [comment]
I think this is a really good idea. I have a feeling that this is something we were hoping to do with Scikitlearn. We may have even had this functionality at one point. @fairbrot do you remember this? In any case, I think have our own CV is better. I haven't had a chance to look through all the code yet, but I will by Monday.

**Comment by chris-nemeth** [comment]
Nice to have a new mean function! Would it be difficult to extend CV to the mean and log-noise parameters?

**Comment by maximerischard** [comment]
The gradient for the mean and noise parameters is implemented (I forgot to delete the TODO).

**Comment by evanmunro** [comment]
Is there an example somewhere that uses the cross-validation related functions that are implemented?

**Pull request merged**
