### PR TITLE
Implemented The Elliptical Slice Sampler

### PR DESCRIPTION
**Pull request by Red-Portal**
Implemented the elliptical slice sampler (ESS) as described in,
```
Murray, Iain, Ryan P. Adams, and David JC MacKay. "Elliptical slice sampling." 
Journal of Machine Learning Research 9 (2010): 541-548.
```
I named the function as `ess` but please change it accordingly.
I think changing  `mcmc` to `hmc` would be more an appropriate but breaking change?
To implement sampling from the hyperparameter priors, I added `sample_params` in both `GPE.jl` and `GPMC.jl`
I didn't have the time to benchmark against HMC but I believe ESS is much more efficient.
Also, ESS doesn't have any hyperparameters so it's pretty easy to use.

I have one question though,
why `post` in `hmc` is row-major while the adjoint is returned?
I think declaring it in column-major order would be more efficient and cleaner.

### CODE REVIEW

**Comment by thomaspinder** [comment]
This looks great, thanks @Red-Portal! I'll review the PR later today.

Are you able to write a few tests for future stability, please?

**Comment by Red-Portal** [comment]
@thomaspinder I'll do that once I have time to spare. I guess about next week or so!

**Comment by thomaspinder** [comment]
No problem @Red-Portal!

**Comment by thomaspinder** [comment]
Hi @Red-Portal. Have you had a chance to look at this? I have some time this week so can help to get this pull request through.

**Comment by Red-Portal** [comment]
I'm sorry, I didn't have time to work on it. I'll surely work on this in the weekend.

**Comment by thomaspinder** [comment]
Sure @Red-Portal. If you need help with anything, then just let me know. 

Also, just make sure you're working from the current version as `GPMC` has been deprecated in favour of `GPA`.

**Pull request merged**
