### PR TITLE
Sparse fix

### PR DESCRIPTION
**Pull request by thomaspinder**
Fix `copy!()` error in full_scale_approximation.jl.

### CODE REVIEW

**Comment by maximerischard** [comment]
Hi @thomaspinder, I'm just looking at this now. What was the original issue you were fixing? The idea of the original code was to fill in the blocks of K without causing memory allocations.

**Comment by thomaspinder** [comment]
Hi @maximerischard. Yes it made sense what you were doing, but the tests were failing when the `copy!()` was called on a `SubArray` - what appeared to be the default output from a `@view` call. 

At the time of merging this pull request, all tests passed. However, the SpecialFunctions package updated the `lgamma()` function and in trying to rectify this, I think @chris-nemeth has inadvertently undone the commits from my merge.

Happy to communicate over email if you want to discuss this more.

**Comment by chris-nemeth** [comment]
The `lgamma` issue is easy to fix. For the sparse stuff, it might be that we've made changes that weren't necessary. Perhaps @maximerischard, could roll back to your last commit and check that it passes the sparse unit tests?

**Comment by maximerischard** [comment]
Here are three things that I currently find confusing:
1. I just ran the tests under commit ff02ea4 in julia v1.1 and v1.2 and all tests passed (although I had to add `StatsBase` to `test/REQUIRE`), so I still don't understand what the problem was.
2. As far as I can see, the changes in this PR have been rolled back by more recent commits.
3. I don't understand why I wrote `copy!(@view(K[ind,ind]), mat(pd))` in the first place rather than just`K[ind,ind] = mat(pd)`.

So my proposal is 5d622272, but I may very well be missing something.

Note: the tests are currently not passing due to issues with `predictMVN` which I will look at now.

**Comment by maximerischard** [comment]
Here's a proposal for `predictMVN`: 35d1acb9376c3e34652a71fb2fa5ec118ab0e3bb

**Comment by chris-nemeth** [comment]
Thanks for looking at this. I'll test out your commit and see if it passes the tests. Perhaps @thomaspinder could also test this out?

**Comment by thomaspinder** [comment]
Just committed to cleanup a fix for the `lgamma()` issue. All tests passing for me now @chris-nemeth.

**Pull request merged**
